script: bundle exec rake test

sudo: false

cache: bundler

branches:
  only: master

rvm:
  - 2.1.8
  - 2.2.4
  - 2.3.0
  - jruby

gemfile:
  - gemfiles/rails3.2.gemfile
  - gemfiles/rails4.1.gemfile
  - gemfiles/rails4.2.gemfile
  - gemfiles/rails5.0.gemfile

matrix:
  exclude:
    - rvm: 2.1.8
      gemfile: gemfiles/rails5.0.gemfile
    - rvm: jruby
      gemfile: gemfiles/rails5.0.gemfile
