script: bundle exec rake test

sudo: false

cache: bundler

branches:
  only: master

rvm:
  - 2.2.7
  - 2.3.4
  - 2.4.2
  - jruby

gemfile:
  - gemfiles/rails3.2.gemfile
  - gemfiles/rails4.2.gemfile
  - gemfiles/rails5.0.gemfile
  - gemfiles/rails5.1.gemfile

matrix:
  exclude:
    - rvm: 2.4.2
      gemfile: gemfiles/rails3.2.gemfile
    - rvm: 2.4.2
      gemfile: gemfiles/rails4.2.gemfile
    - rvm: jruby
      gemfile: gemfiles/rails5.0.gemfile
    - rvm: jruby
      gemfile: gemfiles/rails5.1.gemfile
  include:
    - rvm: 2.3.4
      script: bundle exec rubocop
      gemfile: gemfiles/rails5.1.gemfile
