script: bundle exec rake test

sudo: false

cache: bundler

branches:
  only: master

rvm:
  - 2.3
  - 2.4
  - 2.5
  - jruby-9.1.9.0

gemfile:
  - gemfiles/rails4.2.gemfile
  - gemfiles/rails5.0.gemfile
  - gemfiles/rails5.1.gemfile

matrix:
  exclude:
    - rvm: jruby-9.1.9.0
      gemfile: gemfiles/rails5.0.gemfile
    - rvm: jruby-9.1.9.0
      gemfile: gemfiles/rails5.1.gemfile
  include:
    - rvm: 2.3.4
      script: bundle exec rubocop
      gemfile: gemfiles/rails5.1.gemfile
